# Generated by Django 4.2.25 on 2025-10-05 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_number', models.CharField(max_length=10, verbose_name='Số bàn')),
                ('desk_name', models.CharField(max_length=100, verbose_name='Tên bàn')),
                ('service_type', models.TextField(help_text='Các loại dịch vụ được phục vụ tại bàn này', verbose_name='Loại dịch vụ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bàn phục vụ',
                'verbose_name_plural': 'Các bàn phục vụ',
                'ordering': ['desk_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this location is currently operational'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(help_text='Full address of the location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Name of the public administration center', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(help_text='State/Province where the location is situated', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user can log in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='walkin.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Người dùng'), ('admin', 'Người quản trị')], default='user', help_text='User role determining access level', max_length=20),
        ),
        migrations.CreateModel(
            name='WalkInQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=20, verbose_name='Số thứ tự')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('service_type', models.CharField(max_length=100, verbose_name='Loại dịch vụ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('waiting', 'Đang chờ'), ('in_progress', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã huỷ')], default='waiting', max_length=20, verbose_name='Trạng thái')),
                ('is_priority', models.BooleanField(default=False, help_text='Người già, khuyết tật, phụ nữ mang thai', verbose_name='Ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Giờ vào hàng')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Giờ gọi')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Giờ bắt đầu phục vụ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Giờ hoàn thành')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='walkin.desk', verbose_name='Bàn phục vụ')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_queues', to='walkin.location', verbose_name='Địa điểm')),
            ],
            options={
                'verbose_name': 'Hàng đợi',
                'verbose_name_plural': 'Hàng đợi',
                'ordering': ['-is_priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='desk',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='walkin.location', verbose_name='Địa điểm'),
        ),
        migrations.AlterUniqueTogether(
            name='desk',
            unique_together={('location', 'desk_number')},
        ),
    ]
